/**
*This file is automatically generated by Flash Builder to compile FlexUnit classes and is not intended for modification.
*Please click on the "Refresh" icon in "FlexUnit Results" view to regenerate this file.
*/

/**
 * ------------------------------------------------------------
 * Copyright (c) 2011 Dareville.
 * This software is the proprietary information of Dareville.
 * All Right Reserved.
 * ------------------------------------------------------------
 *
 * SVN revision information:
 * @version $Revision: $:
 * @author  $Author: $:
 * @date    $Date: $:
 */
package
{
	import as3bootstrap.common.BootstrapLoadTest;
	import as3bootstrap.common.BootstrapProgressTest;
	import as3bootstrap.common.BootstrapTestSuite;
	import as3bootstrap.common.services.FontServiceTest;
	import as3bootstrap.common.services.StylesheetServiceTest;
	import as3bootstrap.common.services.XmlServiceTest;
	
	import flash.display.Sprite;
	
	/**
	 * FlexUnitCompilerApplication
	 * 
	 * @author krisrange
	 */
	public class FlexUnitCompilerApplication extends Sprite
	{
		//---------------------------------------------------------------------
		//
		//  Public methods
		//
		//---------------------------------------------------------------------
		
		/**
		 * Constructor
		 */
		
		private var as3bootstrap_common_services_XmlServiceTest_obj:as3bootstrap.common.services.XmlServiceTest;
		private var as3bootstrap_common_BootstrapProgressTest_obj:as3bootstrap.common.BootstrapProgressTest;
		private var as3bootstrap_common_services_StylesheetServiceTest_obj:as3bootstrap.common.services.StylesheetServiceTest;
		private var as3bootstrap_common_services_FontServiceTest_obj:as3bootstrap.common.services.FontServiceTest;
		private var as3bootstrap_common_BootstrapLoadTest_obj:as3bootstrap.common.BootstrapLoadTest;
		private var as3bootstrap_common_BootstrapTestSuite_obj:as3bootstrap.common.BootstrapTestSuite;
		
		//----------------------------------
		//  Override
		//----------------------------------
		
		//---------------------------------------------------------------------
		//
		//  Protected methods
		//
		//---------------------------------------------------------------------
		
		//----------------------------------
		//  Override
		//----------------------------------
		
		//---------------------------------------------------------------------
		//
		//  Private methods
		//
		//---------------------------------------------------------------------
		
		//----------------------------------
		//  Handlers
		//----------------------------------
		
		//---------------------------------------------------------------------
		//
		//  Getter/Setter methods
		//
		//---------------------------------------------------------------------
	}
}