/**
*This file is automatically generated by Flash Builder to compile FlexUnit classes and is not intended for modification.
*Please click on the "Refresh" icon in "FlexUnit Results" view to regenerate this file.
*/

package
{
	import as3bootstrap.common.BootstrapLoadTest;
	import as3bootstrap.common.BootstrapProgressTest;
	import as3bootstrap.common.BootstrapTestSuite;
	import as3bootstrap.common.services.XmlServiceTest;
	
	import flash.display.Sprite;
	
	/**
	 * FlexUnitCompilerApplication
	 *
	 * @langversion ActionScript 3.0
	 * @playerversion Flash 9.0.124
	 * 
	 * @author krisrange 
	 */
	public class FlexUnitCompilerApplication extends Sprite
	{
		//----------------------------------
		//  UI components
		//----------------------------------
		
		//---------------------------------------------------------------------
		//
		//  Public methods
		//
		//---------------------------------------------------------------------
		
		
		private var as3bootstrap_common_services_XmlServiceTest_obj:as3bootstrap.common.services.XmlServiceTest;
		private var as3bootstrap_common_BootstrapLoadTest_obj:as3bootstrap.common.BootstrapLoadTest;
		private var as3bootstrap_common_BootstrapProgressTest_obj:as3bootstrap.common.BootstrapProgressTest;
		private var as3bootstrap_common_BootstrapTestSuite_obj:as3bootstrap.common.BootstrapTestSuite;
		
		//----------------------------------
		//  Override
		//----------------------------------
		
		//---------------------------------------------------------------------
		//
		//  Protected methods
		//
		//---------------------------------------------------------------------
		
		//----------------------------------
		//  Override
		//----------------------------------
		
		//---------------------------------------------------------------------
		//
		//  Private methods
		//
		//---------------------------------------------------------------------
		
		//----------------------------------
		//  Handlers
		//----------------------------------
		
		//---------------------------------------------------------------------
		//
		//  Getter/Setter methods
		//
		//---------------------------------------------------------------------
	}
}